name: sipapparong_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.1.1+4

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  flutter_color_models: ^1.3.2
  shared_preferences: ^2.0.15
  string_validator: ^0.3.0
  google_fonts: ^3.0.1
  dotted_border: ^2.0.0+3
  provider: ^6.0.4
  another_flushbar: ^1.12.29
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  skeletons: ^0.0.3
  skeleton_text: ^3.0.0
  midtrans_sdk: ^0.3.4
  flutter_dotenv: ^5.0.2
  flutter_gen: ^0.0.5
  flutter_native_splash: ^2.2.16
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/logo-splash-screen.png
    - asset/images/logo-login.png
    - asset/images/tagihan-lunas.png
    - asset/images/default.png
    - .env
